<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="40215" started-at="2020-07-11T12:28:46Z" finished-at="2020-07-11T12:29:26Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="40215" started-at="2020-07-11T12:28:46Z" finished-at="2020-07-11T12:29:26Z">
      <class name="hraPOrtal.TestPackage.LoginTest">
        <test-method status="PASS" signature="appiumServerStart()[pri:0, instance:hraPOrtal.TestPackage.LoginTest@7fac631b]" name="appiumServerStart" is-config="true" duration-ms="29133" started-at="2020-07-11T17:58:46Z" finished-at="2020-07-11T17:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumServerStart -->
        <test-method status="PASS" signature="login()[pri:0, instance:hraPOrtal.TestPackage.LoginTest@7fac631b]" name="login" duration-ms="11057" started-at="2020-07-11T17:59:15Z" finished-at="2020-07-11T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="appiumStopServer()[pri:0, instance:hraPOrtal.TestPackage.LoginTest@7fac631b]" name="appiumStopServer" is-config="true" duration-ms="0" started-at="2020-07-11T17:59:26Z" finished-at="2020-07-11T17:59:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at hraPortal.BasePackage.appiumLaunch.appiumserverstop(appiumLaunch.java:78)
	at hraPOrtal.TestPackage.LoginTest.appiumStopServer(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:958)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumStopServer -->
      </class> <!-- hraPOrtal.TestPackage.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
